server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/productdb
    password: Claire@1
  jpa:
    hibernate:
      ddl-auto: update
